apiVersion: batch/v1
kind: Job
metadata:
  name:  hellojob
spec:

  #activeDeadlineSeconds: 10
  #completions: 5
  #backoffLimit: 2
  #parallelism: 2
   
  template:
    metadata:
      name:  hellojob
    spec:
      containers:
      - image: alpine
        name: alpine-hello-container
        command: ["/bin/echo", "Hello Kubernetes"]
      restartPolicy: Never  
