apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  labels:
    software: reverse-proxy
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "10Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "200m"
  
