apiVersion: v1
kind: Pod
metadata:
  name: busybox-by-env
  
spec:
  containers:
  - name: mybusybox
    image: busybox
    command: ["bin/sh"]
    args: ["-c", "sleep 600"]
    env:
      - name: myusername
        valueFrom:
            secretKeyRef:
              name: busybox-secret
              key: username

