apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name:  mycronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name:  mycronjob
        spec:
          containers:
          - image: alpine
            name: alpine-echo-cont
            command: ["/bin/echo", "Hello Kubernetes !!!"]
          restartPolicy: Never

