apiVersion: v1
kind: Pod
metadata:
  name: initcontainer-pod
  labels:
    app: myapp
spec:
  containers:
  - name: my-container
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']

  initContainers:
  - name: my-init-container-1
    image: busybox
    #command: ['sh', '-c', 'echo my-init-container-1 start; sleep 2;echo my-init-container-1 complete;']
    command: ["/bin/echo", "Hello Kubernetes from init container1 "]
  - name: my-init-container-2
    image: busybox
    #command: ['sh', '-c', 'echo my-init-container-2 start; sleep 2;echo my-init-container-2 complete;']
    command: ["/bin/echo", "Hello Kubernetes from init container2 "]
